

services:
  app:
    image: my-django-image
    container_name: my-docker-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"   # API для Django
      - "9001:9001"   # веб-интерфейс
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data

volumes:
  minio_data:
